version: '3.8'
services:
  mongo:
    image: mongo:4.2
    container_name: x-notify-mongo
    ports:
     - target: 27017
       published: 27016
       protocol: tcp
       mode: host
    networks:
     - x-notify-net
  redis:
    image: redis:6.0.1
    container_name: x-notify-redis
    ports:
     - "6379:6379"
    networks:
     - x-notify-net
  x-notify:
    build: ./
    container_name: x-notify
    ports: 
     - "8080:8080"
    restart: on-failure
    environment:
     - MONGODB_URI=mongodb://mongo:27017/test
     - NODE_ENV=development
    depends_on:
     - mongo
    volumes:
     - .:/x-notify
     - /node_modules
    networks:
     - x-notify-net
networks:
  x-notify-net:
    driver: bridge
